// Generated by tools/extract_bb_sdk.py - do not edit.
// Source: stock /ar8030soc/ar_ldy_gnd (statically linked newer SDK).
//
// Authoritative bb_ioctl payload sizes. The shipped
// libar8030_client.so carries an OLDER table: it is missing commands
// entirely (bb_ioctl then returns -2 without sending anything) and
// has a zero iptsize for others (the command goes out with an empty
// payload, which looks like success).

#pragma once
#include <stdint.h>

typedef struct { int req; int iptsize; int outsize; } bb_ioctl_size_t;

static const bb_ioctl_size_t bb_ioctl_sizes_v2[] = {
    { 0x00000012,     19,      0 },  // CFG    18
    { 0x00000002,   1132,      0 },  // CFG    2
    { 0x01000000,      2,    300 },  // GET    0
    { 0x01000001,      0,    164 },  // GET    1
    { 0x01000002,      0,      4 },  // GET    2
    { 0x01000003,      1,    401 },  // GET    3
    { 0x01000004,      4,    160 },  // GET    4
    { 0x01000005,      1,     32 },  // GET    5
    { 0x0100000B,      2,    128 },  // GET    11
    { 0x0100000C,      0,      4 },  // GET    12
    { 0x01000006,      2,      8 },  // GET    6
    { 0x0100000A,      0,   1028 },  // GET    10
    { 0x01000064,      4,    256 },  // GET    100
    { 0x01000065,      8,   1024 },  // GET    101
    { 0x01000066,      0,      1 },  // GET    102
    { 0x01000007,      0,      1 },  // GET    7
    { 0x01000008,      1,      2 },  // GET    8
    { 0x01000009,      0,      3 },  // GET    9
    { 0x01000069,      0,    136 },  // GET    105
    { 0x010000C8,    256,    256 },  // GET    200
    { 0x0100000D,     32,     32 },  // GET    13
    { 0x0100006A,      1,    128 },  // GET    106
    { 0x0100000E,      8,    132 },  // GET    14
    { 0x0100006B,      4,    216 },  // GET    107
    { 0x0100000F,      0,      4 },  // GET    15
    { 0x01000010,      4,    648 },  // GET    16
    { 0x01000011,      4,    648 },  // GET    17
    { 0x0100006C,      4,      1 },  // GET    108
    { 0x0100006D,      4,      1 },  // GET    109
    { 0x0100006E,      0,      1 },  // GET    110
    { 0x0100006F,      0,      1 },  // GET    111
    { 0x01000070,      0,      4 },  // GET    112
    { 0x01000071,      4,      4 },  // GET    113
    { 0x01000072,      0,      8 },  // GET    114
    { 0x01000012,      0,    129 },  // GET    18
    { 0x01000013,      2,     12 },  // GET    19
    { 0x01000014,      0,    136 },  // GET    20
    { 0x01000015,      0,    136 },  // GET    21
    { 0x02000002,     14,      0 },  // SET    2
    { 0x02000003,      4,      0 },  // SET    3
    { 0x02000004,    402,      0 },  // SET    4
    { 0x02000005,      1,      0 },  // SET    5
    { 0x02000006,      2,      0 },  // SET    6
    { 0x0200000C,      2,      0 },  // SET    12
    { 0x0200000D,      2,      0 },  // SET    13
    { 0x02000064,    260,      0 },  // SET    100
    { 0x02000065,   1024,      0 },  // SET    101
    { 0x02000066,      0,      0 },  // SET    102
    { 0x02000067,      3,      0 },  // SET    103
    { 0x02000068,      1,      0 },  // SET    104
    { 0x02000007,      1,      0 },  // SET    7
    { 0x02000008,      2,      0 },  // SET    8
    { 0x02000009,      3,      0 },  // SET    9
    { 0x02000069,      8,      0 },  // SET    105
    { 0x0200006A,      2,      0 },  // SET    106
    { 0x0200006B,      2,      0 },  // SET    107
    { 0x0200006E,      4,      0 },  // SET    110
    { 0x0200000A,   1024,      4 },  // SET    10
    { 0x0200000B,     16,      4 },  // SET    11
    { 0x0200006C,      1,      0 },  // SET    108
    { 0x0200006D,      1,      0 },  // SET    109
    { 0x0200006F,      0,      0 },  // SET    111
    { 0x02000070,      0,      0 },  // SET    112
    { 0x02000072,      0,      0 },  // SET    114
    { 0x02000073,      0,      0 },  // SET    115
    { 0x020000C8,    256,      0 },  // SET    200
    { 0x020000C9,   1024,      0 },  // SET    201
    { 0x020000CA,   1024,      0 },  // SET    202
    { 0x020000CB,   1024,      0 },  // SET    203
    { 0x0200000E,      4,      0 },  // SET    14
    { 0x0200000F,      1,      0 },  // SET    15
    { 0x02000010,      1,      0 },  // SET    16
    { 0x02000011,      1,      0 },  // SET    17
    { 0x02000012,      1,      0 },  // SET    18
    { 0x02000013,      1,      0 },  // SET    19
    { 0x02000027,      1,      0 },  // SET    39
    { 0x02000028,      4,      0 },  // SET    40
    { 0x02000014,      0,      0 },  // SET    20
    { 0x02000015,    136,      0 },  // SET    21
    { 0x02000016,      3,      0 },  // SET    22
    { 0x02000017,     20,      0 },  // SET    23
    { 0x02000018,      3,      0 },  // SET    24
    { 0x02000019,      1,      0 },  // SET    25
    { 0x0200001A,      1,      0 },  // SET    26
    { 0x0200001B,      4,      0 },  // SET    27
    { 0x0200001C,      1,      0 },  // SET    28
    { 0x0200001D,      1,      0 },  // SET    29
    { 0x02000020,      2,      0 },  // SET    32
    { 0x02000022,     10,      0 },  // SET    34
    { 0x02000023,    129,      0 },  // SET    35
    { 0x02000024,     16,      0 },  // SET    36
    { 0x02000025,      4,      0 },  // SET    37
    { 0x02000026,    136,      0 },  // SET    38
    { 0x06000000,   1031,   1031 },  // REMOTE 0
};

#define BB_IOCTL_SIZES_V2_N 94

// Commands absent from the shipped libar8030_client.so table.
#define BB_GET_WORK_CHAN_LIST 0x01000012  // out=129
#define BB_SET_WORK_CHAN_LIST 0x02000023  // in=129

// Payload for both of the above. Reconstructed from ar_ldy_gnd's
// fpv_bb_set_work_chan_list(): it zeroes 128 bytes plus one, writes the
// count at [0], then memcpy()s `count` channel indices at [1].
typedef struct {
    uint8_t chan_num;
    uint8_t chan_idx[128];
} bb_work_chan_list_t;

